---
title: "Red Wine Quality Exploration"
author: Domtria Simba M
date: '2016-02-10'
slug: red-wine-quality-exploratory-analysis
categories: 
  - exploratory analysis
  - visualization
#tidy: 'styler'
description: "This was to explore the variables, structure, patterns, oddities and underlying relationships of a data set of my choice. I chose the Red Wine dataset"
draft: no
editor_options:
  chunk_output_type: console
tags: 
  - R
banner: "img/blog-images/header-images/2016-02-10-udacity-project-red-wine-quality.png"
---



<div id="analysis" class="section level1">
<h1>Analysis</h1>
<p>The scope of this analysis is to understand which chemical properties influence the quality of Red wine.The following <a href="https://archive.ics.uci.edu/ml/datasets/Wine+Quality" target="_blank">data set</a> was utilized in this analysis.
This tidy data set contains 1,599 red wines with 11 variables on the chemical properties of the wine.</p>
<div id="load-the-data-and-required-libraries" class="section level3">
<h3>Load the Data and required Libraries</h3>
<pre class="r"><code>library(ggplot2)
library(grid)
library(gridExtra)
library(psych)
library(dplyr)
library(data.table)

# Local data csv file
dataWine &lt;- &quot;../../static/data/wineQualityReds.csv&quot;

# Name of unzipped Directory
dirFile &lt;- &quot;UCI HAR Dataset&quot;

# Download the dataset (. ZIP), if it does not exist
if (file.exists(dataWine) == FALSE) {
  # Sometimes changing https to http and skip method=&quot;curl&quot; 
  # in the download.file works if having problems with curl
  fileUrl &lt;- &quot;https://s3.amazonaws.com/udacity-hosted-downloads/ud651/wineQualityReds.csv&quot;
  download.file(fileUrl, destfile = &quot;../../static/data/wineQualityReds.csv&quot;)
}

redwine &lt;- fread(dataWine)</code></pre>
</div>
<div id="summary-of-the-data-set" class="section level3">
<h3>Summary of the Data Set</h3>
<pre><code>##  [1] &quot;V1&quot;                   &quot;fixed.acidity&quot;        &quot;volatile.acidity&quot;    
##  [4] &quot;citric.acid&quot;          &quot;residual.sugar&quot;       &quot;chlorides&quot;           
##  [7] &quot;free.sulfur.dioxide&quot;  &quot;total.sulfur.dioxide&quot; &quot;density&quot;             
## [10] &quot;pH&quot;                   &quot;sulphates&quot;            &quot;alcohol&quot;             
## [13] &quot;quality&quot;</code></pre>
<pre><code>## Classes &#39;data.table&#39; and &#39;data.frame&#39;:   1599 obs. of  13 variables:
##  $ V1                  : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ fixed.acidity       : num  7.4 7.8 7.8 11.2 7.4 7.4 7.9 7.3 7.8 7.5 ...
##  $ volatile.acidity    : num  0.7 0.88 0.76 0.28 0.7 0.66 0.6 0.65 0.58 0.5 ...
##  $ citric.acid         : num  0 0 0.04 0.56 0 0 0.06 0 0.02 0.36 ...
##  $ residual.sugar      : num  1.9 2.6 2.3 1.9 1.9 1.8 1.6 1.2 2 6.1 ...
##  $ chlorides           : num  0.076 0.098 0.092 0.075 0.076 0.075 0.069 0.065 0.073 0.071 ...
##  $ free.sulfur.dioxide : num  11 25 15 17 11 13 15 15 9 17 ...
##  $ total.sulfur.dioxide: num  34 67 54 60 34 40 59 21 18 102 ...
##  $ density             : num  0.998 0.997 0.997 0.998 0.998 ...
##  $ pH                  : num  3.51 3.2 3.26 3.16 3.51 3.51 3.3 3.39 3.36 3.35 ...
##  $ sulphates           : num  0.56 0.68 0.65 0.58 0.56 0.56 0.46 0.47 0.57 0.8 ...
##  $ alcohol             : num  9.4 9.8 9.8 9.8 9.4 9.4 9.4 10 9.5 10.5 ...
##  $ quality             : int  5 5 5 6 5 5 5 7 7 5 ...
##  - attr(*, &quot;.internal.selfref&quot;)=&lt;externalptr&gt;</code></pre>
<pre><code>##        V1         fixed.acidity   volatile.acidity  citric.acid   
##  Min.   :   1.0   Min.   : 4.60   Min.   :0.1200   Min.   :0.000  
##  1st Qu.: 400.5   1st Qu.: 7.10   1st Qu.:0.3900   1st Qu.:0.090  
##  Median : 800.0   Median : 7.90   Median :0.5200   Median :0.260  
##  Mean   : 800.0   Mean   : 8.32   Mean   :0.5278   Mean   :0.271  
##  3rd Qu.:1199.5   3rd Qu.: 9.20   3rd Qu.:0.6400   3rd Qu.:0.420  
##  Max.   :1599.0   Max.   :15.90   Max.   :1.5800   Max.   :1.000  
##  residual.sugar     chlorides       free.sulfur.dioxide total.sulfur.dioxide
##  Min.   : 0.900   Min.   :0.01200   Min.   : 1.00       Min.   :  6.00      
##  1st Qu.: 1.900   1st Qu.:0.07000   1st Qu.: 7.00       1st Qu.: 22.00      
##  Median : 2.200   Median :0.07900   Median :14.00       Median : 38.00      
##  Mean   : 2.539   Mean   :0.08747   Mean   :15.87       Mean   : 46.47      
##  3rd Qu.: 2.600   3rd Qu.:0.09000   3rd Qu.:21.00       3rd Qu.: 62.00      
##  Max.   :15.500   Max.   :0.61100   Max.   :72.00       Max.   :289.00      
##     density             pH          sulphates         alcohol     
##  Min.   :0.9901   Min.   :2.740   Min.   :0.3300   Min.   : 8.40  
##  1st Qu.:0.9956   1st Qu.:3.210   1st Qu.:0.5500   1st Qu.: 9.50  
##  Median :0.9968   Median :3.310   Median :0.6200   Median :10.20  
##  Mean   :0.9967   Mean   :3.311   Mean   :0.6581   Mean   :10.42  
##  3rd Qu.:0.9978   3rd Qu.:3.400   3rd Qu.:0.7300   3rd Qu.:11.10  
##  Max.   :1.0037   Max.   :4.010   Max.   :2.0000   Max.   :14.90  
##     quality     
##  Min.   :3.000  
##  1st Qu.:5.000  
##  Median :6.000  
##  Mean   :5.636  
##  3rd Qu.:6.000  
##  Max.   :8.000</code></pre>
</div>
<div id="observations-from-the-summary" class="section level3">
<h3>Observations from the Summary</h3>
<p>The range for fixed acidity is quite high. It has a minimum of 3.8, maximum of 15.9 and a median of 7.90.<br />
The median sugar of red wine is 2.20.<br />
The median quality of red wine is 6.0.<br />
The median pH of red wine is 3.31.<br />
The median alcohol content of red wine is 10.20.</p>
</div>
<div id="understand-the-correlation-of-all-variables" class="section level2">
<h2>Understand the correlation of all variables</h2>
<p>I will start by looking at all variables to get a sense of how they correlate to each other within the data set.</p>
<div id="scatterplot-matrices-review" class="section level3">
<h3>Scatterplot Matrices Review</h3>
<p><img src="/blog/2016-02-10-udacity-project-red-wine-quality_files/figure-html/Scatterplot%20Correlation%20Matrices%20Review-1.png" width="672" /></p>
<p>Pairs.panel output indicates the following correlation behavior:</p>
<div id="fixed-acidity" class="section level4">
<h4>Fixed Acidity</h4>
<p>Noticeable positive correlation with citric acid, density and sulphates. Negative correlation with pH and Alcohol</p>
</div>
<div id="sulphates" class="section level4">
<h4>Sulphates</h4>
<p>Positive correlation with quality, citric acid and chlorides. Negative correlation with pH and residual sugar</p>
</div>
<div id="ph" class="section level4">
<h4>pH</h4>
<p>Positive correlation with Alcohol and Volatile Acidity. Negative correlation with fixed acidity, residual sugar, chlorides and Total SO2</p>
</div>
<div id="alcohol" class="section level4">
<h4>Alcohol</h4>
<p>Positive correlation with pH and quality. Negative Correlation with density, chlorides, total and free so2</p>
</div>
<div id="quality" class="section level4">
<h4>Quality</h4>
<p>Positive correlation with alcohol and sulphates. Negative correlation with density,chlorides,volatile acidity</p>
<p>Based on pairs.panel scatterplot matrices, I will further explore the following components: fixed acidity, pH, sulphates, density, quality and alcohol.
### Distribution analysis key components
<img src="/blog/2016-02-10-udacity-project-red-wine-quality_files/figure-html/Distirbution%20fixed.acidity,pH,sulphates,alcohol-1.png" width="672" /></p>
<p>The following observations were obtained from the above plot:</p>
<ol style="list-style-type: decimal">
<li>The fixed acidity value seems to display a normal distribution between 5.0 and 10.</li>
<li>The pH value seems to display a normal distribution between 3.0 and 3.5.</li>
<li>The sulphates seems to have a slight right skew with a single peak around 0.6.</li>
<li>The alcohol content seems to be right skewed and varies from 8 to 14 with many peaks in the distribution.</li>
<li>None of these distribution have any outliers.</li>
</ol>
<p>A similar distribution analysis for quality is given below:
### Quality Distribution
<img src="/blog/2016-02-10-udacity-project-red-wine-quality_files/figure-html/Quality-1.png" width="672" /></p>
<p>The spread for the quality of red wine exhibits a normal distribution with a peak at quality rating of 5.</p>
</div>
</div>
<div id="scatterplot-review" class="section level3">
<h3>Scatterplot Review</h3>
<p><img src="/blog/2016-02-10-udacity-project-red-wine-quality_files/figure-html/Scatterplot%20Review%20fixed.acidity,%20pH,%20sulphates,%20alcohol,%20quality-1.png" width="672" /></p>
<ol style="list-style-type: decimal">
<li>There is an interesting observation that as quality rating increases, red wine alcohol and PH increases.</li>
<li>Another observation is quality and alcohol increase between 0.75 to 1.0 contents of sulphates.</li>
<li>Quality of wine increased as density decreased at above alcohol content of 10.</li>
</ol>
<p>First, I am going to explore some of those variables that had negative correlation with each other.</p>
</div>
<div id="does-alcohol-have-a-negative-correlation-with-density" class="section level3">
<h3>Does alcohol have a negative correlation with density?</h3>
<p><img src="/blog/2016-02-10-udacity-project-red-wine-quality_files/figure-html/Alcohol,%20density%20correlation-1.png" width="672" /></p>
<p>As expected, the more Alcohol content, the less dense the liquid becomes.</p>
</div>
<div id="does-alcohol-have-a-negative-correlation-with-total-sulfur-dioxide" class="section level3">
<h3>Does alcohol have a negative correlation with total sulfur dioxide?</h3>
<p><img src="/blog/2016-02-10-udacity-project-red-wine-quality_files/figure-html/Alcohol,%20total%20sulfur%20dioxide%20correlation-1.png" width="672" /></p>
<p>This was not expected. Value of total sulfur dioxide decreases, and starts to increase at Alcohol content of around 12.</p>
</div>
<div id="does-ph-have-a-negative-correlation-with-fixed-acidity" class="section level3">
<h3>Does pH have a negative correlation with fixed acidity?</h3>
<p><img src="/blog/2016-02-10-udacity-project-red-wine-quality_files/figure-html/PH,%20fixed%20acidity%20correlation-1.png" width="672" /></p>
<p>As expected in red wine, fixed acidity decreases as PH increases.</p>
</div>
<div id="does-ph-have-a-negative-correlation-with-sulphates" class="section level3">
<h3>Does pH have a negative correlation with sulphates?</h3>
<p><img src="/blog/2016-02-10-udacity-project-red-wine-quality_files/figure-html/Alcohol,%20sulphates%20correlation-1.png" width="672" /></p>
<p>As expected in red wine, sulphates decrease as PH increases.</p>
<p>Second, I am going to explore some of those variables that had positive correlation with each other.</p>
</div>
<div id="do-sulphates-have-a-positive-correlation-with-quality" class="section level3">
<h3>Do sulphates have a positive correlation with quality?</h3>
<p><img src="/blog/2016-02-10-udacity-project-red-wine-quality_files/figure-html/Sulphates,%20quality%20correlation-1.png" width="672" /></p>
<p>As expected Sulphates increase as quality increases.</p>
</div>
<div id="does-alcohol-have-a-positive-correlation-with-quality" class="section level3">
<h3>Does alcohol have a positive correlation with quality?</h3>
<p><img src="/blog/2016-02-10-udacity-project-red-wine-quality_files/figure-html/Alcohol,%20quality%20correlation-1.png" width="672" /></p>
<p>As expected, quality increased as alcohol content increased.</p>
</div>
<div id="does-alcohol-and-density-have-any-effect-on-quality" class="section level3">
<h3>Does alcohol and density have any effect on quality?</h3>
<p><img src="/blog/2016-02-10-udacity-project-red-wine-quality_files/figure-html/Effects%20of%20Alcohol%20and%20density%20on%20quality-1.png" width="672" /></p>
<p>As expected there is a negative correlation between density and alcohol based on the slope for all quality ratings. Effects on quality by alcohol and density is clearly represented in quality rating 6 because it has the steepest negative slope.</p>
</div>
<div id="does-ph-and-fixed-acidity-have-any-effect-on-quality" class="section level3">
<h3>Does pH and fixed acidity have any effect on quality?</h3>
<p><img src="/blog/2016-02-10-udacity-project-red-wine-quality_files/figure-html/Effects%20of%20pH%20and%20fixed%20acidity%20on%20quality-1.png" width="672" /></p>
<p>At quality rating 5, 6 and 7 I see the highest concentration of fixed acidity and pH interaction. I also notice that they are both at pH range of 3.0 - 3.75 and fixed acidity range of 4 - 14. As expected the acidity levels decrease as pH levels increase. However, the steepest negative slopes are seen in quality rating 6,7 and 8</p>
</div>
<div id="does-ph-and-sulphates-have-any-effect-on-quality" class="section level3">
<h3>Does pH and sulphates have any effect on quality</h3>
<p><img src="/blog/2016-02-10-udacity-project-red-wine-quality_files/figure-html/Effects%20of%20pH%20and%20sulphates%20on%20quality-1.png" width="672" /></p>
<p>The general trend is that sulphates decline as pH increases. For quality rating 5 and 6, I do not see a steep negative slope of sulphates as pH increases. I also see a very noticeable trend in quality rating 7 and 8. There is no noticeable decline in sulphates as pH increases. I can conclusively say that on higher quality rating, wine sulphates stay the same as pH increases.</p>
<hr />
</div>
</div>
</div>
<div id="final-plots-and-summary" class="section level1">
<h1>Final Plots and Summary</h1>
<div id="final-plot-one" class="section level3">
<h3>Final Plot One</h3>
<div id="does-alcohol-by-volume-have-any-effect-on-quality" class="section level4">
<h4>Does alcohol % by volume have any effect on quality?</h4>
<p><img src="/blog/2016-02-10-udacity-project-red-wine-quality_files/figure-html/Final_Plot_One-1.png" width="672" /></p>
<p>From the above analysis plot, there seems to be a relation between Alcohol content and quality in terms of the spread. That relationship is very strong in quality rating 6,7 and 8. However, there was an unexpected observation of higher alcohol probability in quality rating 3 and 5. My expectation was higher quality rating has higher alcohol volume.</p>
</div>
</div>
<div id="final-plot-two" class="section level3">
<h3>Final Plot Two</h3>
<div id="does-ph-and-fixed-acidity-have-any-effect-on-quality-1" class="section level4">
<h4>Does pH and fixed acidity have any effect on quality?</h4>
<p><img src="/blog/2016-02-10-udacity-project-red-wine-quality_files/figure-html/Final_Plot_Two-1.png" width="672" /></p>
<p>From the above analysis plot, there does not seem to be any special relations between pH values, fixed acidity and quality. All quality rating showing that pH values increase as fixed acidity decrease.</p>
</div>
</div>
<div id="final-plot-three" class="section level3">
<h3>Final Plot Three</h3>
<div id="does-fixed-acidity-ph-sulphates-alcohol-have-any-effect-on-quality" class="section level4">
<h4>Does fixed acidity, pH, sulphates, alcohol have any effect on quality?</h4>
<p><img src="/blog/2016-02-10-udacity-project-red-wine-quality_files/figure-html/Final_Plot_Three-1.png" width="672" /></p>
<p>From the above boxplot analysis, sulphates and alcohol seem to increase as quality increases. pH values seem to decrease as quality increases. However, an interesting observation was that fixed acidity does not seem to really change as quality increases, except at quality rating 7.</p>
<hr />
</div>
</div>
</div>
<div id="reflection" class="section level1">
<h1>Reflection</h1>
<p>The red wine data set contains “1599 instances and 11 attributes of a red variant of the Portuguese”Vinho Verde" wine from around 2009“<sup>[<em>1</em>]</sup>. I had no understanding of wine when I started exploring this data set. I started out by doing some research on wine making process. After reading a wine production paper by Linda Bisson. I learned that”wine quality was very much subjective"<sup>[<em>2</em>]</sup>.</p>
<p>That information helped me focus on 11 input variables based on physicochemical tests. “Quality is an output variable based on sensory data”<sup>[<em>1</em>]</sup>. As a first step, I wanted to understand how each of these chemicals interact and correlate with each other. I understood what pH, acidity, alcohol and citric acid were. However, I did not know much about chlorides, density, sulfur dioxide and sulphates. I had to do a lot of reading and research to understand how those chemicals affect quality.</p>
<p>At some point, as I was looking at the EDADataOptions file. I realized that there was a <a href="https://archive.ics.uci.edu/ml/datasets/Wine+Quality" target="_blank">link to a text file</a> which describes the variables and how the data was collected. That text file had descriptions of the attributes and that gave me a better understanding of the variables.</p>
<div id="alcohol-content" class="section level4">
<h4>Alcohol content</h4>
<p>I knew alcohol content is an important parameter considered when a buyer purchases any alcoholic product. My analysis tried to unravel relationship of alcohol content with pH values, sulphates, fixed acidity etc and the impact to quality.</p>
</div>
<div id="ph-value" class="section level4">
<h4>pH value</h4>
<p>I knew pH was important,but not sure how. After research, I learned that the pH of the juice at harvest is also an important variable. Wine pH will impact the nature of microorganisms that can persist in the fermentation and subsequently in the wine. Juice pH typically ranges from 3.0 to 3.8 under ideal conditions.</p>
</div>
<div id="fixed-acidity-1" class="section level4">
<h4>Fixed acidity</h4>
<p>I knew too much acidity was not good. However, as for its contribution to wine, I had no knowledge. After research, I learned that acidity level of the grapes at harvest is very important to the structure of the wine as well as to the composition of the finished wine. Acids contribute sourness, while both acidity and pH influence tartness.</p>
</div>
<div id="sulphates-1" class="section level4">
<h4>Sulphates</h4>
<p>Based on my research, “Sulphates are anti-inflammatory and anti-depressant. They are needed for making stomach acid and digestive enzymes, so that we can break down the food we eat into useful components. They keep the gut wall healthy, so fragments of food that are too large cannot pass through. If they did, it would lead to the production of antibodies, and to allergies. It is also said to detoxify chemicals in foods and drugs, chemicals made by the body and others from the environment”<sup>[<em>3</em>]</sup>. What was confusing was the text file with the description stated that, sulphates were an additive. Did that mean, they were added after wine was made? Or did these sulphates occur naturally in the soil which grapes were grown in?</p>
</div>
<div id="sulfur-dioxide-free-and-total" class="section level4">
<h4>Sulfur dioxide (Free and Total)</h4>
<p>Sulfur dioxide has always been a debatable topic due to the allergic reactions associated with it.</p>
<p>Upon learning all this information, I decided to investigate how if at all those chemicals influenced the quality rating of the red wine.</p>
<p>Some of the learnings from the analysis were as follows:</p>
<ol style="list-style-type: decimal">
<li>The understanding that Red Wine generally is good for you. The analysis proved that higher quality red wine exhibits a higher level of sulphates which are supposed to be good for you.</li>
<li>Quality of red wine had a negative correlation to pH. This analysis did not answer what deterministic role pH plays for wine quality testing by wine experts.</li>
<li>For health conscious buyers, red wine with lower and higher alcohol content exhibited higher SO2 content.</li>
<li>Finally, I quote, “To sum up, judging a wine on just two properties is rather simplistic. There are other factors to consider, for example age”<sup>[<em>4</em>]</sup>.</li>
</ol>
</div>
<div id="references" class="section level3">
<h3>References:</h3>
<ol style="list-style-type: decimal">
<li><a href="https://s3.amazonaws.com/udacity-hosted-downloads/ud651/wineQualityInfo.txt" target="_blank">Wine Quality Info</a></li>
<li><a href="http://lfbisson.ucdavis.edu/PDF/VEN124%20Section%201.pdf" target="_blank">Wine Production</a></li>
<li><a href="http://www.foodsmatter.com/allergy_intolerance/sulphites/articles/sulphates_sulphites.html" target="_blank">Food Matters</a></li>
<li><a href="http://fastml.com/predicting-wine-quality/" target="_blank">Predicting wine quality</a></li>
<li><a href="https://rstudio-pubs-static.s3.amazonaws.com/24803_abbae17a5e154b259f6f9225da6dade0.html" target="_blank">Wine Quality Analysis</a></li>
</ol>
<div id="graphcomment">

</div>
</div>
</div>
